cluster:
  mkdir -p cluster_logs/{rule} &&
  ${{SNAKEMAKE_PROFILE:-../profiles}}/smk-simple-slurm/sbatch_wrap.sh
    --parsable
    --job-name=COVID-vpipe-{rule}-{wildcards}
    --cpus-per-task={threads}
    --mem-per-cpu="$(( {resources.mem_mb} / {threads} ))"
    --time="{resources.runtime}"
    --tmp={resources.disk_mb}
    --output=cluster_logs/{rule}/{rule}-%j.out.log
    --error=cluster_logs/{rule}/{rule}-%j.err.log
    #--mem={resources.mem_mb}
cluster-status: ../profiles/smk-simple-slurm/status-sacct.sh
default-resources:
  #  --partition={resources.partition}
  #- partition=<name-of-default-partition>
  #  --qos={resources.qos}
  #- qos=<name-of-quality-of-service>
  - mem_mb=1000
  - disk_mb=1000
  - runtime=15
restart-times: 1
max-jobs-per-second: 30
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 600
jobs: 120
keep-going: True
rerun-trigger: mtime
rerun-incomplete: True
use-conda: True
#printshellcmds: True
#scheduler: greedy
conda-prefix: "../snake-envs"
#shadow-prefix: "${SCRATCH}/pangolin/shadow"
