name: pybis
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python 
  - pandas
  - numpy
  - pyyaml
  - pip 
  - pytest 
  - texttable 
  - tabulate 
  - requests 
  - click 
  - zope.interface 
  - urllib3 
  - certifi 
  - chardet 
  #- ipykernel
  # for google sheet:
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
  # pybis itself
  - pip:
    - pybis
