#!/bin/bash


usage() { echo "Usage: $0 -s
	-s : singleshot - stops at the first loop if it fails
	-h : this help" 1>&2; exit $1; }

singleshot=0
while getopts "sh" o; do
	case "${o}" in
		s)	singleshot=1   ;;
		h)	usage 0	;;
		*)	usage 1	;;
	esac
done

ring_carillon() {
	# kill any remaining rsync
	if killall -3 rsync; then
		sleep 10
		if killall rsync; then
			sleep 10
			killall -9 rsync
		fi
	fi
	# check if inode limitation "No spoace left on device" is still going on
	if touch b0rk && [[ -f b0rk ]]; then
		rm b0rk
	else
		echo "Aargh: problem writing on storage !!!"
		# TODO use carillon phases
		scriptdir="$(dirname $(which $0))"
		${scriptdir}/belfry  df
		remote_batman="ssh -ni ${HOME}/.ssh/id_ed25519_batman euler.ethz.ch --"
		${remote_batman} df
		date -R
		return 1
	fi
	# run the carrillon script
	timeout -k 5 -s INT 3600 ./carillon
	return 0
}


stopfile="$(dirname $(which $0))/status/stop"

# remove previous abort file
if [[ -e "${stopfile}" ]]; then
	echo "(removing previous stop file)"
	rm "${stopfile}"
fi

echo 'First run...'
ring_carillon || (( singleshot == 0 )) || exit 1

while sleep 1200; do 
	echo 'loop...'
	/usr/bin/kinit -l 10h -k -t $HOME/$USER.keytab ${USER%@*}@D.ETHZ.CH;
	ring_carillon

	# check for abort
	if [[ -e "${stopfile}" ]]; then
		rm "${stopfile}"
		exit 0
	fi

	date -R;
	klist;
done
