#!/bin/bash


usage() { echo "Usage: $0 -s
	-s : singleshot - stops at the first loop if it fails
	-o : output directory" 1>&2; exit $1; }

singleshot=0
while getopts "sh" o; do
	case "${o}" in
		s)	singleshot=1   ;;
		h)	usage 0	;;
		*)	usage 1	;;
	esac
done

ring_carillon() {
    # run the carrillon script
	timeout -k 5 -s INT 2700 ./carillon
	return 0
}

echo 'First run...'
ring_carillon || (( singleshot == 0 )) || exit 1

while sleep 1200; do 
    echo 'loop...'
    /usr/bin/kinit -l 10h -k -t $HOME/$USER.keytab ${USER%@*}@D.ETHZ.CH; 
    ring_carillon
    date -R; 
    klist; 
done
