[ _ ]
basedir=/links/shared/covid19-pangolin/backup/rsv_backups
# sub-directory to hold the sorted samples set
sampleset=sampleset
# sub-directory to hold the RSV sorted samples set
sampleset_rsv=sampleset-rsv
# working sub-directory
working=working
# RSV working sub-directory
working_rsv=working-rsv
# linking instead of copying ?
#  --reflink for CoW filesystems (ZFS, BTRFS)
#  --hardlink for most unix-like filesystems
link=--link
# group on the storage (inside download and sampleset)
storgrp=bsse-covid19-pangolin@d.ethz.ch
# parallel copy jobs
parallel=8
# parallel backup copy jobs
parallelpull=32
# timeout before rsync considers the transfer failed in seconds
rsynctimeout=2000
# SSH connection timeout
contimeout=300
# IO timeout
iotimeout=300
# timeout to wait for 'sync' command: 0: no timeout, "": default, otherwise seconds
synctimeout=0

# username used on the cluster (while we're switching over)
cluster_user=bs-pangolin
# directory where to store the status of the backups
backup_statusdir=/links/shared/covid19-pangolin/backup/rsv_backups/status
# rsync daemon module bfabric downloads
bfabric_downloads_rsv=bfabric-downloads-rsv
# name of the active bfabric project
bfabric_project=p35759
# directory for the viloca results
viloca_backup_subdir=viloca_results
# rync daemon module work-viloca
work_viloca_rsv=work-viloca-rsv
# rsync daemon module work-amplicon-cov
work_amplicon_cov_rsv=work-amplicon-cov-rsv
# directory for the amplicon coverage results
amplicon_cov_backup_subdir=amplicon_cov_results
#rsync daemon module work-uploader
work_uploader_rsv=work-uploader_rsv
#bs-bewi08 directory for uploader backups
uploader_backup_subdir=work-uploader
