#!/bin/bash

. server.conf

: ${fileserver:?}
: ${expname:?}
: ${basedir:=$(pwd)}
: ${download:?}

if [[ $( < ~/.netrc ) =~ machine[[:space:]]+${fileserver}.*?login[[:space:]]+([^[:space:]]+) ]]; then
	username="${BASH_REMATCH[1]}"
else
	echo "cannot find login for machine ${fileserver} in ~/.netrc" >&2
	exit 1
fi

exec lftp -c "mirror --continue --no-perms --no-umask --parallel=16 --loop sftp://${username}@${fileserver}/${expname}/ ${basedir}/${download}"
