#!/bin/bash

. server.conf

: ${fileserver:?}
: ${expname:?}
: ${basedir:=$(pwd)}
: ${download:?}

if [[ $( < ~/.netrc ) =~ machine[[:space:]]+${fileserver}.*?login[[:space:]]+([^[:space:]]+) ]]; then
	username="${BASH_REMATCH[1]}"
else
	echo "cannot find login for machine ${fileserver} in ~/.netrc" >&2
	exit 1
fi

if (( ${#@} )); then
	dir=( "${@/#/ --directory=${expname}/}" )
	source="${dir[*]}"
else
	source="--directory=${expname}/*"
fi

exec lftp -c "set cmd:move-background false; connect sftp://${username}@${fileserver}; mirror --continue --no-perms --no-umask --parallel=16 --loop --target-directory=${basedir}/${download} ${source}"
