#!/bin/bash


if [[ $(hostname) =~ ^euler-ft-0[34]$ ]]; then
	: # we are on the correct machine. Proceed.
else
	echo "currently running on $HOSTNAME, should be euler-ft-03 or -04" 2>&1
	exit 1;
fi

exec lftp -c 'mirror --continue --no-perms --no-umask --parallel=16 --loop sftp://ivan.topolsky@bsse.ethz.ch@bs-openbis04.ethz.ch/BSSE_STADLER_COVID/STADLER_COVID/COVID_V/ /cluster/work/bewi/pangolin/openbis-downloads'
