read only = no
use chroot = no
transfer logging = true
log format = %h %o %f %l %b
log file = log/rsyncd.log

charset = utf8

uid = bs-pangolin
auth users = dryak
secrets file = rsyncd.secrets

[sampleset]
	path = /cluster/project/pangolin/processes/sars_cov_2/vpipe_input/
	comment = Samples set
	auth users = belfry:wo batman:ro dryak:rw ceciliav:ro auguste:ro
	incoming chmod = Dg+s,ug+rw,o-rwx

[vpipe_input]
	path = /cluster/project/pangolin/processes/sars_cov_2/vpipe_input/
	comment = Samples set
	auth users = belfry:wo batman:ro dryak:rw ceciliav:ro auguste:ro
	incoming chmod = Dg+s,ug+rw,o-rwx

[sampleset_influenza]
    path = /cluster/project/pangolin//processes/influenza/vpipe_input/
    comment = Samples set
    auth users = belfry:wo batman:ro dryak:rw ceciliav:ro
    incoming chmod = Dg+s,ug+rw,o-rwx

[sampleset-rsv]
        path = /cluster/project/pangolin/processes/rsv/vpipe_input/
        comment = Samples set for RSV analysis
        auth users = belfry:wo batman:ro dryak:rw ceciliav:ro auguste:ro
        incoming chmod = Dg+s,ug+rw,o-rwx

[working]
	path = /cluster/project/pangolin/processes/sars_cov_2/vpipe_output
	comment = Working directory
	auth users = belfry:ro batman:ro dryak:rw ceciliav:ro auguste:ro alison:ro
	outgoing chmod = Dg+s,ug+rw,o-rwx

[remote_status]
		path = /cluster/project/pangolin/processes/status/
		comment = Workdir for sync status files
		auth users = belfry:ro batman:ro dryak:rw
		outgoing chmod = Dg+s,ug+rw,o-rwx

[remote_status_rsv]
		path = /cluster/project/pangolin/processes/rsv/status/
		comment = Workdir for sync status files for rsv analysis
		auth users = belfry:ro batman:ro dryak:rw
		outgoing chmod = Dg+s,ug+rw,o-rwx

[remote_status_influenza]
                path = /cluster/project/pangolin/processes/influenza/status/
                comment = Workdir for sync status files for influenza analysis
                auth users = belfry:ro batman:ro dryak:rw
                outgoing chmod = Dg+s,ug+rw,o-rwx

[bfabric-downloads]
		path = /cluster/project/pangolin/data/fgcz_raw
		comment = Workdir for sync bfabric raw data
		auth users = belfry:ro batman:ro dryak:rw
		outgoing chmod = Dg+s,ug+rw,o-rwx

[work-amplicon-cov]
                path = /cluster/project/pangolin/processes/sars_cov_2/amplicon-coverage/
                comment = Workdir for the amplicon coverage scripts
                auth users = belfry:ro batman:ro dryak:rw
                outgoing chmod = Dg+s,ug+rw,o-rwx

[lollipop]
		path = /cluster/project/pangolin/processes/lollpop/
		comment = Workdir for the lollipop vpipe section
		auth users = belfry:ro batman:ro dryak:rw                
                outgoing chmod = Dg+s,ug+rw,o-rwx
