[ _ ]
# labs: SFTP synchronisation
# (except in case of abnormally slow operation, sync can be left active)
skipsync=
# labs: sample sorting and import
# (set to 0 for labs whose sequences we aren't currently importing, e.g. due to problems)
declare -A lab
lab=( ['gfb']=0 ['fgcz']=1 ['h2030']=0 ['viollier']=0 )
# NOTE: h2030 isn't sequencing as the number of cases is lower.
# pass '--force' to force overwriting any existing file when moving
sort_force=--force
# base wastewater dir
wwdir=/app
# base directory
basedir=${wwdir}/workdir
# sub-directory containing the scripts
scriptdir=${wwdir}/fgcz_sync ###CHANGED
# directory containing the entire git repository, for logging purposes
codebase=${wwdir}/codebase
# sub-directory to hold the sorted samples set
# working sub-directory
# linking instead of copying ?
#  --reflink for CoW filesystems (ZFS, BTRFS)
#  --hardlink for most unix-like filesystems
link=--link
# Installation directory of miniconda3
baseconda=${wwdir}/miniconda3
# File containing the Rsync password
rsync_pass=/home/bs-pangolin/.ssh/rsync.pass.euler

# group on the storage (inside download and sampleset)
# storgrp=bsse-covid19-pangolin@d.ethz.ch
storgrp=bs-pangolin-group
# parallel copy jobs
parallel=8
# parallel backup copy jobs
parallelpull=4
# whereto push the sequences at the end
#releasedir=/links/shared/covid19-pangolin/pangolin/consensus_data/batch/
#releasedir=$(realpath $(pwd)/batch)
# timeout before rsync considers the transfer failed in seconds
rsynctimeout=2000
# SSH connection timeout
contimeout=300
# IO timeout
iotimeout=300
# suspend jobs submission in case of problems
donotsubmit=0
# skip or run ShoRAH step of V-pipe
run_shorah=0
# mail
mailfrom='Automation-carillon<bs-pangolin@ethz.ch>'
mailto=
# timeout for the whole automation loop
runtimeout=7200
# timeout to wait for 'sync' command: 0: no timeout, "": default, otherwise seconds
synctimeout=0
# directory containing the local copy of the dataset
local_dataset=/app/dataset

# Cluster config
# username used on the cluster (while we're switching over)
cluster_user=bs-pangolin
cluster=euler.ethz.ch
clusterdir="/cluster/project/pangolin/fgcz_sync_automation/pangolin/fgcz_sync" 
clusterdir_old="/cluster/project/pangolin"
working="working"
sampleset="sampleset"
# rsyncd module to sync from the remote status folder
remote_status=remote_status
# rsyncd module to sync from the remote bfabric sync folder
bfabric_downloads=bfabric-downloads
#rsyncd module to sync to the remote uploader work folder
#work_uploader=work-uploader
# Directory containing the git repository of V-pipe
vpipe_code=/cluster/project/pangolin/V-pipe
#Directory for fgcz download outside of the virus automation folder same as 'download' folder in fgcz.conf
# fgcz_download_folder="/cluster/project/pangolin/bfabric-downloads/p23224"

# BSSE folder backups config
# Do we want to backup the FGCZ mirror?
backup_fgcz_raw=1
# the user of the remote machine used for backup
bck_user=bs-pangolin
# the hostname of the remote machine used for backup
bckhost=d@bs-bewi08

# Status tracking configuration
statusdir=${basedir}/status
lockfile=${statusdir}/carillon_lock
