#!/usr/bin/env bash
umask 0007
. /cluster/project/pangolin/resources/miniconda3/bin/activate 'base'
mkdir --mode=0770 -p "${SCRATCH}/pangolin/"{shadow,temp}

#echo "INI -> YAML"
#flock -x -o config.yaml -c "anyconfig_cli -O yaml -o config.yaml -I ini vpipe.config"
#sync
#sleep 1
#flock -x -o config.yaml -c "echo config unlocked"


exec -a "$0" snakemake -s "/cluster/project/pangolin/processes/V-pipe/workflow/Snakefile" --conda-frontend conda --conda-prefix "/cluster/project/pangolin/resources/snake-envs" --shadow-prefix "${SCRATCH}/pangolin/shadow" --rerun-trigger mtime --use-conda "$@"
