#!/usr/bin/env bash
. ../miniconda3/bin/activate 'base'
mkdir --mode=0770 -p "${SCRATCH}/pangolin/"{shadow,temp}
exec -a "$0" snakemake -s "../V-pipe/vpipe.snake" --conda-prefix "../snake-envs" --shadow-prefix "${SCRATCH}/pangolin/shadow" --use-conda "$@"
